### ISSUE TITLE
KakfaUser does not create mentioned secret automatically

### ISSUE THREAD

**Issue by laukik85** [banzaicloud/koperator#664]
After creating KafkaUser CRD does not create appropriate secret. I am using following yaml to create KafkaUser.

apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: user
  namespace: kb
spec:
  clusterRef:
    name: kafka
  secretName: user-secret
  createCert: false

**Comment by baluchicken** [comment]
Thanks for opening this issue can you please provide your full kafkaCluster CR.

**Comment by laukik85** [comment]
@baluchicken Thanks for responding. Please find attached full KafkaCluster CR.
[10-1-kafkacluster.txt](https://github.com/banzaicloud/koperator/files/7131506/10-1-kafkacluster.txt)

**Comment by laukik85** [comment]
@baluchicken Let me know if you need any other details.

**Comment by baluchicken** [comment]
@laukik85 Based on your kafkaCluster CR, you are not configuring the cluster to use SSL. The reason why this is important is your kafkaUser CR using cert-manager to issue a certificate. For Cert-manager to issue a cert it requires something called ClusterIssuer or Issuer resources which can use to generate your certs. Since the kafka cluster does not use SSL no ClusterIssuer generated by the operator so the kafkauser controller with the provided CR cannot generate anything.
On the other hand you set `createCert: false` which also disables cert generation I suggest to remove that line altogether.
You have two options create a new cluster with ssl enabled or create your own clusterissuer resource for cert manager and use https://github.com/banzaicloud/koperator/blob/master/config/samples/example-user-with-pkibackend.yaml user example to tell the controller which clusterissuer should be used to issue a certificate.

**Comment by baluchicken** [comment]
Closing this since the issue is stale for a while, please reopen if it still stands.
