### ISSUE TITLE
broker pod  keeps restarting

### ISSUE THREAD

**Issue by wongearl** [banzaicloud/koperator#881]
When creating a kafka cluster, there is always a broker pod that keeps restarting

**Comment by hi-im-aren** [comment]
Hey wongearl, could you provide some more information using the template below? We need more info so we can help 🙂

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the issue:**
Please describe the steps to reproduce the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem like release numberm version, branch, etc.
