### ISSUE TITLE
How to install kafka operator using kubectl

### ISSUE THREAD

**Issue by liqunlin** [banzaicloud/koperator#932]
helm install kafka-operator --namespace=kafka --create-namespace banzaicloud-stable/kafka-operator

How to install kafka operator using kubectl？

**Comment by bartam1** [comment]
Hello!
You can get this information from here: https://github.com/banzaicloud/koperator/blob/c470369e520f8756a73960765a8e4ffda624b44a/Makefile#L110

**Comment by pregnor** [comment]
Hey there,

You can find the documentation of the installation here: https://banzaicloud.com/docs/supertubes/kafka-operator/install-kafka-operator/#manual-install.

If for some reason the Kustomize approach Márton shared wouldn't work for you and you want to use `kubectl` instead of Helm, you should deploy the the CRD files first from the https://github.com/banzaicloud/koperator/tree/v0.23.0/config/base/crds directory (`kubectl create --validate=false -f https://github.com/banzaicloud/koperator/releases/download/v0.23.0/kafka-operator.crds.yaml`) and then generate the resource manifests based on the Helm template files locally (`helm template kafka-operator ${koperator_repo}/charts/kafka-operator`) and then `kubectl create ...` the resulting resources.

Let us know if this is anything else to help you with or we can close the ticket.

**Comment by panyuenlau** [comment]
@liqunlin Please don't hesitate to join out [Slack channel](https://community-banzaicloud.slack.com/?redir=%2Farchives%2FCK75ATB29) where we can better provide the help that you need
